on:
  push:
    branches:
      - legacy
  pull_request:
name: linkinator-check
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: pages/
          concurrency: 1
          markdown: true
